---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u4320599/public_html/albertjohannes/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R boostrap $DEPLOYPATH